name = "MovingLeastSquares"
uuid = "ca385d51-68f7-42d6-b76e-818d6d6c9c2c"
authors = ["Ali Kazemzadeh <alikazemzadeh.sh@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
